use kataru::*;
use kataru_ffi::build_codegen_consts;

#[test]
fn test_build_codegen_consts() {
    println!("Generating code.");
    let story = Story::load("tests/data/story").unwrap();
    let source = build_codegen_consts(&story).unwrap();
    println!("{}", source);

    assert_eq!(
        source,
        r###"/// DO NOT EDIT.
/// This file was autogenerated by Kataru based on your scripts.

namespace Kataru
{
    public static partial class Namespaces
    {
        public const string Global = "global",
            Room1 = "Room1",
            Room2 = "Room2";

        private static readonly string[] all = {
            Global,
            Room1,
            Room2
        };
    }

    public static partial class Passages
    {
        public const string None = "",
            EndDialogue = "EndDialogue",
            Room1_RedSlimeTalk = "Room1:RedSlimeTalk",
            Room1_RedSlimeTrigger = "Room1:RedSlimeTrigger",
            Room2_AngryGreen = "Room2:AngryGreen",
            Room2_BlueSlimeTalk = "Room2:BlueSlimeTalk",
            Room2_GiveGoop = "Room2:GiveGoop",
            Room2_GreenObserve = "Room2:GreenObserve",
            Room2_NoGiveGoop = "Room2:NoGiveGoop",
            Room2_Poster = "Room2:Poster",
            Room2_ThanksGoop = "Room2:ThanksGoop",
            Start = "Start";

        private static readonly string[] all = {
            None,
            EndDialogue,
            Room1_RedSlimeTalk,
            Room1_RedSlimeTrigger,
            Room2_AngryGreen,
            Room2_BlueSlimeTalk,
            Room2_GiveGoop,
            Room2_GreenObserve,
            Room2_NoGiveGoop,
            Room2_Poster,
            Room2_ThanksGoop,
            Start
        };
    }

    public static partial class Characters
    {
        public const string None = "",
            GlobalLight = "GlobalLight",
            Room1_Party = "Room1:Party",
            Room1_PartyLight = "Room1:PartyLight",
            Room1_RedSlime = "Room1:RedSlime",
            Room2_BlueSlime = "Room2:BlueSlime",
            Room2_GreenSlime = "Room2:GreenSlime",
            Slime = "Slime",
            Think = "Think";

        private static readonly string[] all = {
            None,
            GlobalLight,
            Room1_Party,
            Room1_PartyLight,
            Room1_RedSlime,
            Room2_BlueSlime,
            Room2_GreenSlime,
            Slime,
            Think
        };
    }
}
"###
    );
    println!("{}", source);
}
