/// DO NOT EDIT.
/// This file was autogenerated by Kataru based on your scripts.

namespace Kataru
{
    public static partial class Namespaces
    {
        public const string Global = "global";

        private static readonly string[] all = {
            Global
        };
    }

    public static partial class Passages
    {
        public const string None = "";

        private static readonly string[] all = {
            None
        };
    }

    public static partial class Characters
    {
        public const string None = "";

        private static readonly string[] all = {
            None
        };
    }
}
