/// Kataru Constants.
/// This file provides the public interface into the automatically generated
/// set of constants and enums for idenitifers in Kataru.
/// See `Constants.Generated.cs` for the generated code. Do not edit manually.
/// NOTE: Enum representations (Namespace, Character, Passage) are NOT safe to serialize, as they are not guaranteed to correspond the the same string.
/// When serializing (i.e. setting values in the editor) prefer using the string representation.
/// Only use enums when hardcoding values in source code.

using System.Linq;

namespace Kataru
{
    /// <summary>
    /// Autogenerated class containing all namespace strings and a wrapper Enum.
    /// </summary>
    public static partial class Namespaces
    {
        /// <summary>
        /// Get all namespace names.
        /// </summary>
        public static string[] All() => all;
    }

    /// <summary>
    /// Autogenerated class containing all passage strings and a wrapper Enum.
    /// </summary>
    public static partial class Passages
    {
        /// <summary>
        /// Get all passage names.
        /// </summary>
        public static string[] All() => all;

        /// <summary>
        /// Get all passage names in a given namespace.
        /// This requires a linear search over all passage names, so don't do this at runtime.
        /// </summary>
        public static string[] InNamespace(string @namespace) => Utils.FilterByNamespace(all, @namespace);
    }

    /// <summary>
    /// Autogenerated class containing all character strings and a wrapper Enum.
    /// </summary>
    public static partial class Characters
    {
        /// <summary>
        /// Get all character names.
        /// </summary>
        public static string[] All() => all;

        /// <summary>
        /// Get all character names in a given namespace.
        /// This requires a linear search over all passage names, so don't do this at runtime.
        /// </summary>
        public static string[] InNamespace(string @namespace) => Utils.FilterByNamespace(all, @namespace);
    }

    /// <summary>
    /// Basic utils for Kataru constants.
    /// </summary>
    static class Utils
    {
        /// <summary>
        /// Returns all identifiers that belong to a given namespace.
        /// </summary>
        public static string[] FilterByNamespace(string[] identifiers, string @namespace)
        {
            // Global namespaces don't have any "namespace:" prepended.
            System.Func<string, bool> predicate;
            if (@namespace == Namespaces.Global)
            {
                predicate = identifier => identifier == "None" || !identifier.Contains(":");
            }
            else
            {
                predicate = identifier => identifier == "None" || identifier.StartsWith(@namespace + ":");
            }

            return identifiers.
                Where(predicate).
                ToArray<string>();
        }
    }
}